# Generated by Django 6.0.4 on 2026-05-06 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_interaccion_enlace_reunion_alter_compromiso_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaccion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_interacciones', to='core.interaccion'),
        ),
    ]
