# Generated by Django 6.0.4 on 2026-06-02 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_interaccion_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmaDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_content', models.TextField(blank=True, null=True)),
                ('pdf_attachment', models.FileField(blank=True, null=True, upload_to='firmas_pdf/')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firma_digital', to='core.usuario')),
            ],
        ),
    ]
