// server/models/userSignature.js
const db = require('./db');

/**
 * Save or update the HTML signature for a user.
 * @param {string} userId - UUID or integer identifier of the user.
 * @param {string} html   - HTML string generated by the WYSIWYG editor.
 */
async function saveSignature(userId, html) {
  const query = `INSERT INTO user_signatures (user_id, html_signature, updated_at)
                 VALUES ($1, $2, NOW())
                 ON CONFLICT (user_id) DO UPDATE SET
                   html_signature = EXCLUDED.html_signature,
                   updated_at = NOW();`;
  await db.query(query, [userId, html]);
}

/**
 * Retrieve the stored HTML signature for a user.
 * @param {string} userId
 * @returns {string} html signature (or empty string if none).
 */
async function getSignature(userId) {
  const result = await db.query(
    'SELECT html_signature FROM user_signatures WHERE user_id = $1',
    [userId]
  );
  if (result.rowCount === 0) return '';
  return result.rows[0].html_signature;
}

module.exports = { saveSignature, getSignature };
